<?php
$tablemeta = array (
  'id' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'id',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 5,
    'num' => 0,
  ),
  'organizationcode' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'organizationcode',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 1,
  ),
  'name' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'name',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 4,
    'num' => 2,
  ),
  'type' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'type',
    'type' => 253,
    'gentype' => 'string',
    'len' => 24,
    'flags' => 0,
    'num' => 3,
  ),
  'visit_address' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'visit_address',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 4,
  ),
  'visit_address2' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'visit_address2',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 5,
  ),
  'visit_zipcode' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'visit_zipcode',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 6,
  ),
  'visit_city' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'visit_city',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 7,
  ),
  'visit_state' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'visit_state',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 8,
  ),
  'visit_country' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'visit_country',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 9,
  ),
  'mail_address' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'mail_address',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 10,
  ),
  'mail_address2' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'mail_address2',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 11,
  ),
  'mail_zipcode' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'mail_zipcode',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 12,
  ),
  'mail_city' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'mail_city',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 13,
  ),
  'mail_state' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'mail_state',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 14,
  ),
  'mail_country' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'mail_country',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 15,
  ),
  'invoice_address' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'invoice_address',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 16,
  ),
  'invoice_address2' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'invoice_address2',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 17,
  ),
  'invoice_zipcode' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'invoice_zipcode',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 18,
  ),
  'invoice_city' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'invoice_city',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 19,
  ),
  'invoice_state' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'invoice_state',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 20,
  ),
  'invoice_country' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'invoice_country',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 21,
  ),
  'phone' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'phone',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 22,
  ),
  'fax' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'fax',
    'type' => 253,
    'gentype' => 'string',
    'len' => 60,
    'flags' => 0,
    'num' => 23,
  ),
  'email' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'email',
    'type' => 253,
    'gentype' => 'string',
    'len' => 150,
    'flags' => 0,
    'num' => 24,
  ),
  'website' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'website',
    'type' => 253,
    'gentype' => 'string',
    'len' => 300,
    'flags' => 0,
    'num' => 25,
  ),
  'bankaccount' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'bankaccount',
    'type' => 253,
    'gentype' => 'string',
    'len' => 90,
    'flags' => 0,
    'num' => 26,
  ),
  'bankaccount2' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'bankaccount2',
    'type' => 253,
    'gentype' => 'string',
    'len' => 90,
    'flags' => 0,
    'num' => 27,
  ),
  'bankaccount3' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'bankaccount3',
    'type' => 253,
    'gentype' => 'string',
    'len' => 90,
    'flags' => 0,
    'num' => 28,
  ),
  'bankaccount4' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'bankaccount4',
    'type' => 253,
    'gentype' => 'string',
    'len' => 90,
    'flags' => 0,
    'num' => 29,
  ),
  'vatnumber' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'vatnumber',
    'type' => 253,
    'gentype' => 'string',
    'len' => 75,
    'flags' => 0,
    'num' => 30,
  ),
  'debtornumber' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'debtornumber',
    'type' => 253,
    'gentype' => 'string',
    'len' => 90,
    'flags' => 0,
    'num' => 31,
  ),
  'member_of' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'member_of',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 32,
  ),
  'status' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'status',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 33,
  ),
  'source' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'source',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 34,
  ),
  'industry' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'industry',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 35,
  ),
  'employees' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'employees',
    'type' => 3,
    'gentype' => 'number',
    'len' => 5,
    'flags' => 0,
    'num' => 36,
  ),
  'revenue' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'revenue',
    'type' => 253,
    'gentype' => 'string',
    'len' => 15,
    'flags' => 0,
    'num' => 37,
  ),
  'rate' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'rate',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 38,
  ),
  'assigned_to' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'assigned_to',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 39,
  ),
  'remark' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'remark',
    'type' => 252,
    'gentype' => 'text',
    'len' => 196605,
    'flags' => 0,
    'num' => 40,
  ),
  'created_by' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'created_by',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 41,
  ),
  'created_on' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'created_on',
    'type' => 12,
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 42,
  ),
  'last_modified_by' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'last_modified_by',
    'type' => 3,
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 43,
  ),
  'last_modified_on' => 
  array (
    'table' => 'organization',
    'table_type' => 'MyISAM',
    'name' => 'last_modified_on',
    'type' => 12,
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 44,
  ),
)
?>