<?php
$tablemeta = array (
  'id' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'id',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 5,
    'num' => 0,
  ),
  'title_id' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'title_id',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 1,
  ),
  'userid' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'userid',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 15,
    'flags' => 0,
    'num' => 2,
  ),
  'lastname' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'lastname',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 4,
    'num' => 3,
  ),
  'firstname' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'firstname',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 4,
  ),
  'initials' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'initials',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 5,
  ),
  'address' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'address',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 6,
  ),
  'zipcode' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'zipcode',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 0,
    'num' => 7,
  ),
  'city' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'city',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 8,
  ),
  'state' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'state',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 9,
  ),
  'country' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'country',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 10,
  ),
  'phone' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'phone',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 0,
    'num' => 11,
  ),
  'cellular' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'cellular',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 0,
    'num' => 12,
  ),
  'fax' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'fax',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 20,
    'flags' => 0,
    'num' => 13,
  ),
  'email' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'email',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 14,
  ),
  'function' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'function',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 50,
    'flags' => 0,
    'num' => 15,
  ),
  'remark' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'remark',
    'type' => 'blob',
    'gentype' => 'text',
    'len' => 65535,
    'flags' => 0,
    'num' => 16,
  ),
  'role' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'role',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 15,
    'flags' => 4,
    'num' => 17,
  ),
  'doj' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'doj',
    'type' => 'date',
    'gentype' => 'date',
    'len' => 10,
    'flags' => 4,
    'num' => 18,
  ),
  'birthdate' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'birthdate',
    'type' => 'date',
    'gentype' => 'date',
    'len' => 10,
    'flags' => 0,
    'num' => 19,
  ),
  'bankaccount' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'bankaccount',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 20,
  ),
  'socialsecuritynumber' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'socialsecuritynumber',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 100,
    'flags' => 0,
    'num' => 21,
  ),
  'functionlevel' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'functionlevel',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 22,
  ),
  'department' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'department',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 23,
  ),
  'employer_id' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'employer_id',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 24,
  ),
  'supervisor' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'supervisor',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 25,
  ),
  'sl_balance' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'sl_balance',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '3,1',
    'flags' => 4,
    'num' => 26,
  ),
  'el_balance' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'el_balance',
    'type' => 'real',
    'gentype' => 'decimal',
    'len' => '3,1',
    'flags' => 4,
    'num' => 27,
  ),
  'status' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'status',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 9,
    'flags' => 0,
    'num' => 28,
  ),
  'lng' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'lng',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 2,
    'flags' => 4,
    'num' => 29,
  ),
  'password' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'password',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 40,
    'flags' => 0,
    'num' => 30,
  ),
  'theme' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'theme',
    'type' => 'string',
    'gentype' => 'string',
    'len' => 14,
    'flags' => 0,
    'num' => 31,
  ),
  'company' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'company',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 32,
  ),
  'created_by' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'created_by',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 33,
  ),
  'created_on' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'created_on',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 34,
  ),
  'last_modified_by' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'last_modified_by',
    'type' => 'int',
    'gentype' => 'number',
    'len' => 10,
    'flags' => 0,
    'num' => 35,
  ),
  'last_modified_on' => 
  array (
    'table' => 'person',
    'table_type' => 'MyISAM',
    'name' => 'last_modified_on',
    'type' => 'datetime',
    'gentype' => 'datetime',
    'len' => 19,
    'flags' => 0,
    'num' => 36,
  ),
)
?>